### ISSUE TITLE
Very large files - >265 gb

### ISSUE THREAD

**Issue by raw937** [linsalrob/fastq-pair#10]
Hello, 

I have some very large metagenomes. R1 and R2 that are >265 gb. I gave fastq_pair a big amount of memory (2 TB). Still taking a long time. 

Any thoughts?

**Comment by linsalrob** [comment]
There are two things to try. First, try changing the hash table size (`-t` option on the command line) which will consume a bit more memory but should make it much faster.

If that doesn't work, you can also try splitting the files into smaller files. Because fastq-pair doesn't alter the sequence IDs, I would probably split the files into a few smaller files based on number of lines (e.g. using the bash `split` command with the `-l` option [make sure your choice is a multiple of 4]), and then run fastq-pair on the split files. Finally, concatenate all the R1 and R2 single reads, and run it once more on those. If you go with this approach, you might also consider just splitting the left reads since fastq-pair indexes those but then streams the right reads and so that file should not take additional memory.

**Comment by raw937** [comment]
How large of a hash size (-t ) should I use? default 100003

**Comment by linsalrob** [comment]
Well, the default is 100003 which is taking a long time, so you should use a number bigger than that! Each entry in the table uses 32 bytes, so this should use ~3 MB of RAM just for the table. You should be able to increase that table size by a lot to make it faster.

The reason that the performance degrades with lots of entries and a small table is that you are turning the hash into a linked list as described at about minute 6 of this video: https://www.youtube.com/watch?v=nVu_OnyGk6U&list=PLpPXw4zFa0uKKhaSz87IowJnOTzh9tiBk&index=33

**Comment by raw937** [comment]
First, I love these videos. I am huge fan. I will give a lot more. 
Thank you so much.

**Comment by raw937** [comment]
I have increased to -t 100000000 but it isn't producing any files. Is there a calculation that I am missing?

**Comment by linsalrob** [comment]
No. Did the code run? 
What was the exit code (`echo $?` from the command line).

**Comment by raw937** [comment]
The command I used was 
fastq_pair file_R1.fastq file_R2.fastq -t 100000000

It ran for a couple of hours. It produced no file outputs or errors (in my sbatch). Normally when I run the default without -t it produces output files. 

I have available memory of 2164211339264.

I thank you so much for your patience.

**Comment by linsalrob** [comment]
Try putting the -t before file_R1.fastq:

`fastq_pair  -t 100000000 file_R1.fastq file_R2.fastq`

**Comment by raw937** [comment]
Will do! Thank you again for your patience. 
Can I use an even larger -t? I want to give it the max amount of memory. My current is 2164211339264.

**Comment by linsalrob** [comment]
Yes, you can increase `-t` until your computer crashes.

**Comment by raw937** [comment]
Great! Love the answer. Thank you so very much!
