### ISSUE TITLE
Error on very large fastq file

### ISSUE THREAD

**Issue by essere** [linsalrob/fastq-pair#12]
Hello, 
I am analyzing a very large fastq file (~240 Gb for each pair).

I have this error when running fastq-pair. 

"We cannot allocate the memory for a table size of -436581356. Please try a smaller value for -t"

Could you provide some solution for this?

Thanks
Sam

**Comment by linsalrob** [comment]
what is the command you are using?

If you are setting `-t` on the command line, you might be setting it _too large_ of a number! It is stored as a [signed int](https://en.wikipedia.org/wiki/Integer_(computer_science)) and so if you set the value too high it may be misinterpreted.

**Comment by essere** [comment]
From your instructions, I get the number of lines by "wc -l".

wc -l Sample.R1.fastq
2548641872

By dividing by 4, I got this number: 637160468
So I tried a command

fastq_pair -t 637160468 Sample.R1.fastq Sample.R2.fastq

Is it ok to use a smaller number than actual reads?

**Comment by linsalrob** [comment]
So that _should_  have been OK (depending on the specific system you used), but yes, I suspect you have an [integer overflow](https://en.wikipedia.org/wiki/Integer_overflow)

Yes, it is OK to use a smaller number than the actual number of reads. Try dividing the number by 4 (159290117). In this case you will end up with, on average, four sequences per bucket.

**Comment by essere** [comment]
Thank you. It worked !

This is the very program I have been looking for.
You are so great !!

**Comment by linsalrob** [comment]
Excellent!
